### PR TITLE
Updated toolchain, impoved multiselects and compatibility to select2 4.1

### PR DESCRIPTION
**Pull request by weberhofer**

### CODE REVIEW

**Comment by weberhofer** [comment]
This RP fixes #49

**Comment by ttskch** [comment]
@weberhofer Thanks for your contribution! I updated toolchain on https://github.com/ttskch/select2-bootstrap4-theme/commit/993dea8b7fd0f755202f26afc066f94ffb8abb7a . And I cannot merge this PR to master branch because it breaks BC for users of select2 4.0. I will create a new branch to support select2 4.1. Please wait a moment. Thanks.

**Comment by tagliala** [comment]
Hi @ttskch 

Select 2 4.1 is now in RC. Most of the things already seems to work, if you create a branch I can help to check the missing ones

**Comment by tagliala** [comment]
[This branch](https://github.com/tagliala/select2-bootstrap4-theme/tree/feature/refactor-as-custom-select) contains an opinionated reimplementation of this theme working with Select2 4.1 RC0

I've used [Bootstrap 4's custom-select](https://getbootstrap.com/docs/4.6/components/forms/#select-menu) to improve uniformity

I've tested on:
- latest Safari macOS 10.15
- latest Chrome macOS 10.15
- latest Firefox macOS 10.15
- latest Chrome on Windows 10
- latest Firefox on Windows 10
- latest Edge on Windows 10
- IE11 on Windows 10

I can't test on IE 10

**Comment by NordicAT** [comment]
@tagliala 
I have tested your reimplementation. I like it, but there seems to be a bug with an empty multiselect.
Have a look at the following screenshot:

Select2-Multiselect

**Comment by tagliala** [comment]
@NordicAT thanks. I've opened a new PR at #67

> I like it, but there seems to be a bug with an empty multiselect.

I've added some extra fields to the demo for testing purposes. Any chance to share the original HTML so I can reproduce?

**Comment by NordicAT** [comment]
@tagliala 
Are you able to replicate the issue by using the following code-snippet?

`
<div class="container">

    
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#home">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#menu1">Menu 1</a>
        </li>
    </ul>

    
    <div class="tab-content">
        <div class="tab-pane container active" id="home">
            <select class="selectMapping form-control select2-multiple" name="test[]" id="test" multiple="multiple">

            </select>
        </div>
        <div class="tab-pane container fade" id="menu1">...</div>
    </div>

</div> 
`

**Comment by tagliala** [comment]
@NordicAT nope. Tested on windows chrome / firefox / edge / ie11

Can we continue at #67? we are off topic here

**Pull request closed without merging**
